language: php

php:
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - mysql -e 'create database laravel;'
  - php artisan migrate --package="cartalyst/sentry" --env=testing
  - php artisan migrate --env=testing
  - php artisan db:seed
  - php artisan createusers:create --minimum="100"
  - php artisan createtutorials:create --minimum="100"
